# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcp_game/game.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tcp_game/game.proto\x12\x04game\"\x1a\n\x07\x43ommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\x0c\"E\n\x13\x44rawingInstructions\x12.\n\x0cinstructions\x18\x01 \x03(\x0b\x32\x18.game.DrawingInstruction\";\n\x12\x44rawingInstruction\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0f\n\x07to_draw\x18\x03 \x01(\t\"\x19\n\x17\x44rawEntireScreenRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tcp_game.game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=29
  _globals['_COMMAND']._serialized_end=55
  _globals['_DRAWINGINSTRUCTIONS']._serialized_start=57
  _globals['_DRAWINGINSTRUCTIONS']._serialized_end=126
  _globals['_DRAWINGINSTRUCTION']._serialized_start=128
  _globals['_DRAWINGINSTRUCTION']._serialized_end=187
  _globals['_DRAWENTIRESCREENREQUEST']._serialized_start=189
  _globals['_DRAWENTIRESCREENREQUEST']._serialized_end=214
# @@protoc_insertion_point(module_scope)
